spring.application.name=notification
server.port=9092

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=
QUEUE_URL=


spring.main.allow-bean-definition-overriding=true

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
MAIL_FROM=${MAIL_FROM}

MAILTRAP_API_TOKEN=${MAILTRAP_API_TOKEN}
MAILTRAP_INBOX_ID=${MAILTRAP_INBOX_ID}